angular.module("planetApp",[]).controller("planetController",function($scope){
    $scope.planets=[
        {name:'Mercury',type:'terrestrial',distance:0.4,moons:0},
        {name:'Satrun',type:'terrestrial',distance:0.4,moons:0},
        {name:'Venus',type:'terrestrial',distance:0.4,moons:0},
        {name:'Mercury',type:'terrestrial',distance:0.4,moons:0},
        {name:'Mercury',type:'terrestrial',distance:0.4,moons:0},
        {name:'Mercury',type:'terrestrial',distance:0.4,moons:0},
        {name:'Mercury',type:'terrestrial',distance:0.4,moons:0},
    ];
});